name: 

# Triggers the workflow on pull request and merge to main
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
  # schedule:
  #   - cron: '40 12 * * 1'

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  INSTRUCTOR_EMAIL: ${{ secrets.INSTRUCTOR_EMAIL }}
  INSTRUCTOR_PWD: ${{ secrets.INSTRUCTOR_PWD }}

jobs:
  bdd-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0' ]
    name: Execute Tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore Packages
        run: dotnet restore
        working-directory: ./poc_bdd
      - name: Install Browsers
        run: pwsh bin/Debug/netX/playwright.ps1 install
        working-directory: ./poc_bdd
      - name: Build
        run: dotnet build
        working-directory: ./poc_bdd
      - name: Run Tests
        run: dotnet test
        working-directory: ./poc_bdd
      - name: Build Report
        run: livingdoc test-assembly bin/Debug/net8.0/poc_bdd.dll -t bin/Debug/net8.0/TestExecution.json --title "Canvas Automation Report" --output ./report/index.html
        working-directory: ./poc_bdd
