name: 

on:
  push:
    branches:
      - master
  schedule:
    # Twice per day
    - cron: '0 0,12 * * *'

env:
  BASE_URL: ${{ vars.BASE_URL }}
  INSTRUCTOR_EMAIL: ${{ secrets.INSTRUCTOR_EMAIL }}
  INSTRUCTOR_PWD: ${{ secrets.INSTRUCTOR_PWD }}

jobs:
  bdd-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0' ]
    name: Execute Tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Restore Packages
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Install Browsers
        run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Install Specflow LivingDoc
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
      - name: Run Tests
        run: dotnet test --filter "Category=automated & Category=regression-suite"
      - name: Build Report
        run: livingdoc test-assembly bin/Debug/net8.0/poc_bdd.dll -t bin/Debug/net8.0/TestExecution.json --title "Canvas Automation Report" --output ./report/index.html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./report
          retention-days: 5
